# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-browsers
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            curl -L  https://qameta.bintray.com/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip -o allure.zip
            unzip ./allure.zip

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir ./reports
            python3 -m pytest -v -n 4 tests --alluredir ./reports
          when: always

      - run:
          name: generate reports
          command: |
            allure-2.7.0/bin/allure generate -c ./reports
          when: always

      - store_artifacts:
          path: ./allure-report
          destination: allure-report
