# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-browsers
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir ./reports
            python3 -m pytest -n 3 tests/ui_tests/test_ui_jira_login.py --alluredir ./reports/
            when: always

      - store_artifacts:
          path: reports
          destination: reports
